### ISSUE TITLE
Videos are not avaliable for people without a Chinese phone number.

### ISSUE THREAD

**Issue by ronaldonunez** [shijieS/people-counting-dataset#1]
I would like to use your dataset to test some algorithms in my research. But, unfortunately, I was not able to download the videos, once they are hosted at pan.baidu.com, which needs a Baidu account to login. I`ve try to register, but there is a verification step, available only for those with a Chinese phone number.

Can you upload them to another service, as Mega, Google Drive or Dropbox?

**Comment by shijieS** [comment]
Thank you for your attention. I'll upload this dataset to Google Drive. It seems to take 20 hours.

**Comment by ronaldonunez** [comment]
OK, thank you.

**Comment by shijieS** [comment]
Hi, I've uploaded this dataset to [Google Drive](https://drive.google.com/drive/folders/1EK_Nfsjudn-Ku0-Q81c454fLBAQnRp-R?usp=sharing).  I'll keep this link active for one month.
