### ISSUE TITLE
Contact information for commercial license

### ISSUE THREAD

**Issue by mattdibi** [shijieS/people-counting-dataset#5]
> License
> The datasets provided on this page are published under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License . This means that you must attribute the work in the manner specified by the authors, you may not use this work for commercial purposes and if you alter, transform, or build upon this work, you may distribute the resulting work only under the same license. If you are interested in commercial usage you can contact us for further options.

Could you provide contact information for commercial usage?

**Comment by shijieS** [comment]
Here is the information:

[contact us](mailto:shijieSun@chd.edu.cn?subject=[GitHub]%20About%20PCDS%20Commercial%20Usage)
